### ISSUE TITLE
HTML and CSS notes as a markdown file.

### ISSUE THREAD

**Issue by Bassanthossamxx** [Bassanthossamxx/GDG-Back-End-Notes#3]
you will upload it in cloned repo and then pull request it and we will review it and add it if it is okay 

> Don’t forget to add the file in the `Web Fundamentals` folder, and ensure it is written as a markdown file with resources (e.g., docs, videos) listed at the end.

**deadline 27/10**
@mennaahmedmmm

**Comment by mennaahmedmmm** [comment]
pull request #6

**Comment by mennaahmedmmm** [comment]
added pull request #7
