### ISSUE TITLE
Web Security note as markdown file

### ISSUE THREAD

**Issue by Bassanthossamxx** [Bassanthossamxx/GDG-Back-End-Notes#5]
Please upload the file to the cloned repository, create a pull request, and we will review it. If everything is in order, we’ll approve the pull request.

> Don’t forget to add the file in the `Web Fundamentals` folder, and ensure it is written as a markdown file with resources (e.g., docs, videos) listed at the end.

**Deadline: 27/10**  

@ahmedmohamadd

**Comment by ahmeddelattarr** [comment]
@ahmedmohamadd your deadline is 29/10 , how's your leader 🤨
